TECH_BUTTONS_DATA = [
    ("Автовышка", "tech:aerial_platform"),
    ("Автогрейдер", "tech:autograder"),
    ("Автокран", "tech:truck_crane"),
    ("Бетоновоз", "tech:concrete_mixer_truck"),
    ("Бульдозер", "tech:bulldozer"),
    ("Каток", "tech:road_roller"),
    ("Контейнер (ПУХТО)", "tech:container_pukhto"),
    ("Манипулятор", "tech:manipulator"),
    ("Мини-погрузчик", "tech:mini_loader"),
    ("Мини-экскаватор", "tech:mini_excavator"),
    ("Поливомоечная(коммунальная) техника", "tech:watering_communal"),
    ("Самосвал", "tech:dump_truck"),
    ("Тонар", "tech:tonar"),
    ("Трактор", "tech:tractor"),
    ("Трал", "tech:trawl"),
    ("Фронтальный погрузчик", "tech:front_loader"),
    ("Шаланда(длинномер)", "tech:flatbed_truck"),
    ("Эвакуатор", "tech:tow_truck"),
    ("Экскаватор гусеничный", "tech:crawler_excavator"),
    ("Экскаватор колесный", "tech:wheeled_excavator"),
    ("Экскаватор-погрузчик", "tech:loader_excavator"),
    ("Ямобур", "tech:auger_drill"),
]
